### ISSUE TITLE
Plan and Profile plot with R

### ISSUE THREAD

**Issue by mrnickbear** [sancarn/Innovyze-ICM-Libraries#10]
Hi Sancarn, I'm new to GitHub and pretty sure Issues are not the right way to categorize this, but wanted to let you know I'm working on an improved plotting system using R.  Currently it relies on passing data through my teams GIS database so can't easily be shared with others yet but I hope to improve on this later and share the code if there's interest.  

Features/improvements over ICM built in plan and profiles:

- All vector graphics, much smaller files
- Rotate plan view to use space efficiently and/or match the orientation of other documents 
- Full control over text and number formats and fonts
- Generate page titles from data in background layers
- Generate table of contents from page titles
- Potential to show more than 2 HGL lines
- Potential to show multiple plans or profiles on a page

**Comment by sancarn** [comment]
Hi @mrnickbear 

It really depends what the implementation is like.

1. If you are using HOOPServer, then I'd add this as an example in [`HoopServer`](https://github.com/sancarn/Innovyze-ICM-Libraries/tree/master/libraries/InfoWorks-ICM/Ruby/HOOPServer)
2. If you just want to produce your own sample using your own API endpoints happy for this to go in it's own folder in [`Ruby`](https://github.com/sancarn/Innovyze-ICM-Libraries/tree/master/libraries/InfoWorks-ICM/Ruby) assuming it uses Ruby under the hood.
3. You can always post your own github repository out there too :) I can always make an `awesome-infoworks` repository which links to this repository and other tools used in the industry (like yours) :)

**Comment by mrnickbear** [comment]
Thanks for the advice and support!  It's going to take me many months to follow through on this but I'll keep at it.  I don't have an exchange license, but yes I did use Ruby to export the network data and results.

Nicholas Bear, PE
San Francisco Public Works
Hydraulic Engineering
________________________________

**Comment by sancarn** [comment]
Feel free to [publish a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) with any changes required :)
